### PR TITLE
fix(): export OutputSelectorFields

### PR DESCRIPTION
**Pull request by chyzwar**
When trying to export selector from shared package we are getting errors. 

```
Exported variable 'xxxxxx' has or is using name 'OutputSelectorFields' from external module "/home/vagrant/Projects/common-2/node_modules/reselect/es/types"
```

Fix is to export OutputSelectorFields

### CODE REVIEW

**Comment by chyzwar** [comment]
It would be nice to get this merged, reselect managed to break our code twice, 4.1.1 and 4.1.2 releases raised TS errors. Because we share selectors across multiple repositories we need to upgrade this in sync otherwise repo with 4.1.0 will throw errors when consuming selectors in version 4.1.1. We cannot upgrade to 4.1.2 because of above error.

**Comment by andymikulski** [comment]
I've also hit this issue, and as a temporary measure have resorted to just editing my local `node_modules` in order to continue work.

**Comment by chyzwar** [comment]
@markerikson Any chance you can take a look at this ?

**Comment by markerikson** [comment]
I've spent my entire last two weekends trying to come up with solutions for #540 and #541.  As of yesterday I _think_ I have a resolution, but it's going to take some additional time to get that work cleaned up and ready.

Once that's done I'm going to look at the `OutputSelectorFields` issue. Per #543 , I may end up actually removing that type, but what I really need is for someone to provide me a repo that demonstrates this problem happening so that I can reproduce the behavior locally and confirm that any fixes work.

So, I understand the concerns, and I'm trying to address them, but the best thing you can do to help is provide a repro for me.

**Comment by Methuselah96** [comment]
There's a repro in redux-devtools if that helps (linked in [the issue](https://github.com/reduxjs/reselect/issues/543)). I only had problems when I had to manually set the generics for `createSelector`.

**Comment by markerikson** [comment]
@Methuselah96 can you narrow it down to a smaller standalone repo?

**Comment by markerikson** [comment]
Hmm. Just an import, not even a "re-export from a shared lib"?

**Comment by Methuselah96** [comment]
Right, the issue is creating a .d.ts file since it can't access `OutputSelectorFields`.

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.3

**Pull request closed without merging**
